name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  SDL_VIDEODRIVER: "dummy"
  SDL_AUDIODRIVER: "disk"

jobs:
  build:
    name: Tests
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.toolchain == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ] #[macos-latest, windows-latest, ubuntu-latest]
        toolchain: [latest, nightly]
        include:
          #- os: macos-latest # uses minute multiplication 10
          #  MACOS: true
          #- os: windows-latest # uses minute multiplication2
          - os: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install linux deps
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends libasound2-dev libudev-dev pkg-config
      if: contains(matrix.os, 'ubuntu')

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
